apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pv-migration-member
subjects:
  - kind: ServiceAccount
    name: pv-migration-member
    namespace: pv-migration-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pv-migration-member
