//go:build !ignore_autogenerated

package v1alpha1

import runtime "k8s.io/apimachinery/pkg/runtime"

func (in *ClusterSnapshot) DeepCopyInto(out *ClusterSnapshot) {
	*out = *in
	if in.CollectedAt != nil {
		in, out := &in.CollectedAt, &out.CollectedAt
		*out = (*in).DeepCopy()
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeMetadata, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClusterSnapshot) DeepCopy() *ClusterSnapshot {
	if in == nil {
		return nil
	}
	out := new(ClusterSnapshot)
	in.DeepCopyInto(out)
	return out
}

func (in *PVMetadata) DeepCopyInto(out *PVMetadata) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PVMetadata) DeepCopy() *PVMetadata {
	if in == nil {
		return nil
	}
	out := new(PVMetadata)
	in.DeepCopyInto(out)
	return out
}

func (in *PVMetadata) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PVMetadataList) DeepCopyInto(out *PVMetadataList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PVMetadata, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PVMetadataList) DeepCopy() *PVMetadataList {
	if in == nil {
		return nil
	}
	out := new(PVMetadataList)
	in.DeepCopyInto(out)
	return out
}

func (in *PVMetadataList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PVMetadataSpec) DeepCopyInto(out *PVMetadataSpec) {
	*out = *in
	out.WorkloadRef = in.WorkloadRef
}

func (in *PVMetadataSpec) DeepCopy() *PVMetadataSpec {
	if in == nil {
		return nil
	}
	out := new(PVMetadataSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PVMetadataStatus) DeepCopyInto(out *PVMetadataStatus) {
	*out = *in
	if in.CollectedAt != nil {
		in, out := &in.CollectedAt, &out.CollectedAt
		*out = (*in).DeepCopy()
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeMetadata, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]ClusterSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PVMetadataStatus) DeepCopy() *PVMetadataStatus {
	if in == nil {
		return nil
	}
	out := new(PVMetadataStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *PVMigration) DeepCopyInto(out *PVMigration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PVMigration) DeepCopy() *PVMigration {
	if in == nil {
		return nil
	}
	out := new(PVMigration)
	in.DeepCopyInto(out)
	return out
}

func (in *PVMigration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PVMigrationList) DeepCopyInto(out *PVMigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PVMigration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PVMigrationList) DeepCopy() *PVMigrationList {
	if in == nil {
		return nil
	}
	out := new(PVMigrationList)
	in.DeepCopyInto(out)
	return out
}

func (in *PVMigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PVMigrationSpec) DeepCopyInto(out *PVMigrationSpec) {
	*out = *in
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeMapping, len(*in))
		copy(*out, *in)
	}
}

func (in *PVMigrationSpec) DeepCopy() *PVMigrationSpec {
	if in == nil {
		return nil
	}
	out := new(PVMigrationSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PVMigrationStatus) DeepCopyInto(out *PVMigrationStatus) {
	*out = *in
	if in.Works != nil {
		in, out := &in.Works, &out.Works
		*out = make([]WorkReference, len(*in))
		copy(*out, *in)
	}
}

func (in *PVMigrationStatus) DeepCopy() *PVMigrationStatus {
	if in == nil {
		return nil
	}
	out := new(PVMigrationStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *VolumeMetadata) DeepCopyInto(out *VolumeMetadata) {
	*out = *in
	in.PVSpec.DeepCopyInto(&out.PVSpec)
}

func (in *VolumeMetadata) DeepCopy() *VolumeMetadata {
	if in == nil {
		return nil
	}
	out := new(VolumeMetadata)
	in.DeepCopyInto(out)
	return out
}

func (in *VolumeMapping) DeepCopyInto(out *VolumeMapping) { *out = *in }
func (in *VolumeMapping) DeepCopy() *VolumeMapping {
	if in == nil {
		return nil
	}
	out := new(VolumeMapping)
	in.DeepCopyInto(out)
	return out
}

func (in *WorkReference) DeepCopyInto(out *WorkReference) { *out = *in }
func (in *WorkReference) DeepCopy() *WorkReference {
	if in == nil {
		return nil
	}
	out := new(WorkReference)
	in.DeepCopyInto(out)
	return out
}

func (in *WorkloadRef) DeepCopyInto(out *WorkloadRef) { *out = *in }
func (in *WorkloadRef) DeepCopy() *WorkloadRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadRef)
	in.DeepCopyInto(out)
	return out
}
